### ISSUE TITLE
Issue With Graphics Memory

### ISSUE THREAD

**Issue by Angu0083** [sebasrock156/Acer-TravelMate-P246-MG-OpenCore#2]
Hello, 

       First of all, Thanks for this post. I successfully installed the Mac OS Sonomo beta on my Dell Inspiron laptop.

 
![image](https://github.com/sebasrock156/Acer-E5-572-TMP246-OpenCore/assets/25692168/0cadf7a1-320b-4e82-9295-be65c40212b1)

      But I am facing an issue with Graphics memory. I have only 7Mb. Also, I am facing error while OpenCore patcher.

![image](https://github.com/sebasrock156/Acer-E5-572-TMP246-OpenCore/assets/25692168/b31d27ad-a1a7-405c-9f58-802b95fdcc2c)

**Comment by sebasrock156** [comment]
Yeah; try to compile OpenCore Legacy Patcher from source; That didn't work for me, but it's Olarila's recommendation; Or try to install MacOS Ventura (If you use any OCLP version may be work).

When using version 0.6.8 and compiling 0.6.9, OCLP would throw a message saying: "OS Not Supported" when trying to patch it so that 3D acceleration would work. Still, there are people for whom these versions work perfectly.

**Comment by sebasrock156** [comment]
> Hello,
> 
> ```
>    First of all, Thanks for this post. I successfully installed the Mac OS Sonomo beta on my Dell Inspiron laptop.
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/25692168/261873127-0cadf7a1-320b-4e82-9295-be65c40212b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzM1NDgsIm5iZiI6MTcwOTIzMzI0OCwicGF0aCI6Ii8yNTY5MjE2OC8yNjE4NzMxMjctMGNhZGY3YTEtMzIwYi00ZTgyLTkyOTUtYmU2NWM0MDIxMmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE5MDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZDRjNTdlM2E5ODkwMjFhNTkzOGMxMmI0NGIxNTJlNmE5Y2E3YzM3MTljOWNmOTJlYTE3MDlmOTBhNmVkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UXLM0PpPED0jn7zx0uubN6y4mUtxjO5hwp6yXJtLUk4)
> 
> ```
>   But I am facing an issue with Graphics memory. I have only 7Mb. Also, I am facing error while OpenCore patcher.
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/25692168/261873250-b31d27ad-a1a7-405c-9f58-802b95fdcc2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzM1NDgsIm5iZiI6MTcwOTIzMzI0OCwicGF0aCI6Ii8yNTY5MjE2OC8yNjE4NzMyNTAtYjMxZDI3YWQtYTFhNy00MDVjLTlmNTgtODAyYjk1ZmRjYzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE5MDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4Y2ViZWRkODI3MTJjMTU2NDk0MGU2NzE3M2JhOWIyZDNmYWVhZmNmMmRkZTc5NDZlZjNlODc4ZDM3MDZhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NCrm4A4-vk7-8HO0KtDn4EHaubEgfEJu8XLxAoUFyBw)

Now 3D Acceleration is fixed with newer OCLP versions (I'm using v1.1.0)

**Comment by Angu0083** [comment]
@sebasrock156 Thanks for information. I'm successfully upgraded to Sonoma 14.3.1, and Graphic Issue was resolved. After install post Patch using OCLP version 1.3.0.


![Screenshot ](https://github.com/sebasrock156/Acer-E5-572-TMP246-OpenCore/assets/25692168/c9727674-bf23-4d22-9cc1-f6dd0baf4cfd)
